# Generated by Django 4.2.5 on 2023-10-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='destination',
        ),
    ]
